default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['AGGRE_DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: aggre_development

test:
  <<: *default
  database: aggre_test

production:
  <<: *default
  database: aggre_production
  username: aggre
  password: <%= ENV['AGGRE_DATABASE_PASSWORD'] %>
